# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common_types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ommon_types.proto\x12\x0fgoogle.protobuf\"\xeb\x01\n\tMatrix4x4\x12\x0c\n\x04r1c1\x18\x01 \x01(\x01\x12\x0c\n\x04r1c2\x18\x02 \x01(\x01\x12\x0c\n\x04r1c3\x18\x03 \x01(\x01\x12\x0c\n\x04r1c4\x18\x04 \x01(\x01\x12\x0c\n\x04r2c1\x18\x05 \x01(\x01\x12\x0c\n\x04r2c2\x18\x06 \x01(\x01\x12\x0c\n\x04r2c3\x18\x07 \x01(\x01\x12\x0c\n\x04r2c4\x18\x08 \x01(\x01\x12\x0c\n\x04r3c1\x18\t \x01(\x01\x12\x0c\n\x04r3c2\x18\n \x01(\x01\x12\x0c\n\x04r3c3\x18\x0b \x01(\x01\x12\x0c\n\x04r3c4\x18\x0c \x01(\x01\x12\x0c\n\x04r4c1\x18\r \x01(\x01\x12\x0c\n\x04r4c2\x18\x0e \x01(\x01\x12\x0c\n\x04r4c3\x18\x0f \x01(\x01\x12\x0c\n\x04r4c4\x18\x10 \x01(\x01\x42\x11\xaa\x02\x0e\x42\x61utiroGrpcLibb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_types_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\016BautiroGrpcLib'
  _globals['_MATRIX4X4']._serialized_start=40
  _globals['_MATRIX4X4']._serialized_end=275
# @@protoc_insertion_point(module_scope)
