# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import ccu_grpc.manual_mode_service_pb2 as manual__mode__service__pb2


class ManualModeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ControlStateStream = channel.unary_stream(
                '/google.protobuf.ManualModeService/ControlStateStream',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=manual__mode__service__pb2.ControlState.FromString,
                )
        self.DriveRpmControlStream = channel.stream_unary(
                '/google.protobuf.ManualModeService/DriveRpmControlStream',
                request_serializer=manual__mode__service__pb2.DriveRpmControlMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DriveArmControl = channel.unary_unary(
                '/google.protobuf.ManualModeService/DriveArmControl',
                request_serializer=manual__mode__service__pb2.DriveArmControlMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SetState = channel.unary_stream(
                '/google.protobuf.ManualModeService/SetState',
                request_serializer=manual__mode__service__pb2.SetStateMessage.SerializeToString,
                response_deserializer=manual__mode__service__pb2.SetStateMessageResponse.FromString,
                )
        self.StartDrill = channel.unary_stream(
                '/google.protobuf.ManualModeService/StartDrill',
                request_serializer=manual__mode__service__pb2.StartDrillMessage.SerializeToString,
                response_deserializer=manual__mode__service__pb2.StartDrillResponse.FromString,
                )
        self.Stop = channel.unary_unary(
                '/google.protobuf.ManualModeService/Stop',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class ManualModeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ControlStateStream(self, request, context):
        """server streams the current state of allowed actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DriveRpmControlStream(self, request_iterator, context):
        """client streams RPM drive commands
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DriveArmControl(self, request, context):
        """unary Arm move commands. returns when the arm has stopped moving
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetState(self, request, context):
        """client requests a state change. Service call streams progress and ends with a SetStateFinishedMessage on completion or fail
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartDrill(self, request, context):
        """start drilling at the current tool position
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop whatever bautiro is doing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManualModeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ControlStateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ControlStateStream,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=manual__mode__service__pb2.ControlState.SerializeToString,
            ),
            'DriveRpmControlStream': grpc.stream_unary_rpc_method_handler(
                    servicer.DriveRpmControlStream,
                    request_deserializer=manual__mode__service__pb2.DriveRpmControlMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DriveArmControl': grpc.unary_unary_rpc_method_handler(
                    servicer.DriveArmControl,
                    request_deserializer=manual__mode__service__pb2.DriveArmControlMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetState': grpc.unary_stream_rpc_method_handler(
                    servicer.SetState,
                    request_deserializer=manual__mode__service__pb2.SetStateMessage.FromString,
                    response_serializer=manual__mode__service__pb2.SetStateMessageResponse.SerializeToString,
            ),
            'StartDrill': grpc.unary_stream_rpc_method_handler(
                    servicer.StartDrill,
                    request_deserializer=manual__mode__service__pb2.StartDrillMessage.FromString,
                    response_serializer=manual__mode__service__pb2.StartDrillResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.protobuf.ManualModeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ManualModeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ControlStateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/google.protobuf.ManualModeService/ControlStateStream',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            manual__mode__service__pb2.ControlState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DriveRpmControlStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/google.protobuf.ManualModeService/DriveRpmControlStream',
            manual__mode__service__pb2.DriveRpmControlMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DriveArmControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.protobuf.ManualModeService/DriveArmControl',
            manual__mode__service__pb2.DriveArmControlMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/google.protobuf.ManualModeService/SetState',
            manual__mode__service__pb2.SetStateMessage.SerializeToString,
            manual__mode__service__pb2.SetStateMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartDrill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/google.protobuf.ManualModeService/StartDrill',
            manual__mode__service__pb2.StartDrillMessage.SerializeToString,
            manual__mode__service__pb2.StartDrillResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.protobuf.ManualModeService/Stop',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
