# REQUEST height in meter
float32 lift_setpoint_position
---
# RESULT
# response_code: check msg.ResponseCode for possible reponse codes
# lift_position: lift position at the end of movement
int32 response_code
float32 lift_position
---